### ISSUE TITLE
Mist

### ISSUE THREAD

**Issue by disc0nn3ct** [ShiftMediaProject/libgcrypt#2]
Miss

**Comment by disc0nn3ct** [comment]
I'm trying to make some big number in string to type gcry_mpi_t, make some operations and than printf it back to output.

**Comment by disc0nn3ct** [comment]
https://stackoverflow.com/questions/15080516/print-unsigned-int-base-10-decimal-value-of-mpi 

And this example doesn't work 
#include <gcrypt.h>
#include <stdio.h>

int main(){
    gcry_error_t err;
    gcry_mpi_t cript_prime;
    unsigned char buffer[401] = {0};
    char number[101] = {0};

    cript_prime = gcry_mpi_new(101);

    strcpy(number, "415325779662433871844955547383752003988573073626");
    gcry_mpi_scan(&cript_prime, GCRYMPI_FMT_USG, number, sizeof(number), NULL);

    err = gcry_mpi_print(GCRYMPI_FMT_USG, buffer, sizeof(buffer), NULL, cript_prime);

    if (err != 0){
      printf("error: %d\n", err);
      return -1;
    }

    printf("The number tested is: %s\n",buffer);

    printf("trying to convert to HEX\n");

    /* get actual value */
    err = gcry_mpi_print(GCRYMPI_FMT_HEX, buffer, sizeof(buffer), NULL, cript_prime);

    if (err != 0){
      gcry_err_code_t code = gcry_err_code(err);
      printf("error: %d\n", code);
      return -1;
    }

    /* print actual value */
    printf("result: %s\n", buffer);

    printf("finished\n");

    return 0;
}

I also confirmed my thoughts using this website: http://www.unitconversion.org/numbers/base-10-to-base-16-conversion.html

This will show that hex (base-16) 48BFDA215C31A9F0B226B3DB11F862450A0F30DA actual is 415325779662433762080404206464628666084640806848 (base-10)

**Comment by Sibras** [comment]
This is the wrong place to post such usage issues. This repo is only for the unofficial SMP Visual studio builds. Usage issues with gcrypt itself should be posted to the official gcrypt issue tracker and should be based off official gcrypt sources.
