### ISSUE TITLE
Using static libraries but getting error of gcrypt.dll not found

### ISSUE THREAD

**Issue by stanley101music** [ShiftMediaProject/libgcrypt#3]
## Context

I'm using the static libraries downloaded from the release page. I've checked the settings of the project configurations including C/C++ and Linker in visual studio 2022, and when I try to run the program, it'll give a system error "This application failed to start because gcrypt.dll was not found. Re-installing the application may fix this problem.". The error can be solved by adding gcrypt.dll to the project folder, but I was wondering if the static library in Releases should be an import library or an object library.

## Expected Behavior
The program can run without adding gcrypt.dll to the project folder

## Actual Behavior
Need to add gcrypt.dll to the project folder to run the program

## Your Environment

* Libgcrypt Release Version Used: libgcrypt_libgcrypt-1.10.0_msvc17.zip
* Operating System and Version: Win 10 21H1
* Compiler/IDE  Version(s): Microsoft Visual Studio Community 2022 17.1.0

**Comment by Sibras** [comment]
You need to add libgcrypt.lib to your linker includes. Note that gcrypt.lib is for the dynamic library and libgcrypt.lib is for the static.

**Comment by stanley101music** [comment]
Thanks, I've removed gcrypt.lib from linker includes, and now it works perfectly
