### ISSUE TITLE
Vcpkg Install?

### ISSUE THREAD

**Issue by elibroftw** [ShiftMediaProject/libgcrypt#4]
## Context

Is it possible to install with vcpkg? Either by getting in touch with vcpkg maintainers or under a new name?

## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used:
* Operating System and Version:
* Compiler and Version(s):

**Comment by Sibras** [comment]
There is already a libgcrypt port for vcpkg. As for windows support there was already an attempt to add SMP support to vcpkg ([https://github.com/microsoft/vcpkg/pull/20433](https://github.com/microsoft/vcpkg/pull/20433)) but as youll see from the PR comments that approach was rejected.

**Comment by elibroftw** [comment]
Wow that sucks.
