### ISSUE TITLE
build RelaseDllWinRT error

### ISSUE THREAD

**Issue by yzf888** [ShiftMediaProject/libgcrypt#5]
build RelaseDllWinRT error
## Context

2>S:\f\dev\ex\shiftMediaProject\libgcrypt\random\rndw32uwp.cpp(51,51): error C2065: 'POINT': undeclared identifier
2>S:\f\dev\ex\shiftMediaProject\libgcrypt\random\rndw32uwp.cpp(51,67): error C2065: 'MEMORYSTATUS': undeclared identifier
2>S:\f\dev\ex\shiftMediaProject\libgcrypt\random\rndw32uwp.cpp(52,18): error C2065: 'FILETIME': undeclared identifier
2>S:\f\dev\ex\shiftMediaProject\libgcrypt\random\rndw32uwp.cpp(52,37): error C2065: 'LARGE_INTEGER': undeclared identifier
## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used: 
* Operating System and Version: win 10
* Compiler and Version(s):  vs2022

**Comment by Sibras** [comment]
Not sure how that one hadnt been detected earlier. Anyway Ive pushed a fix.
