### ISSUE TITLE
[Help]  How to use?   Some steps you need

### ISSUE THREAD

**Issue by bopin2020** [ShiftMediaProject/libgcrypt#7]
Glad to see u compiled libgcrypt-1.10.2 msvc on windows platform. Could you provide me libgcrypt-1.10.2.pdb file or how to build this project on windows Visual Studio. I sufferred too much barriers as this origin project was gnu for linux. Although cross-platform compiled using mingw for windows, and offical github give an example for winx86 but I expected a x64 binary and finally failed to compile x64 arch during compilation. Looking forward to your assist and thanks in advanced.

**Comment by Sibras** [comment]
Within this repository check within the SMP folder which has visual studio project files with x86/x64 and debug/release configurations.

**Comment by bopin2020** [comment]
Error LNK1181	cannot open “libgpg-errord.lib”	libgcrypt	xxx\libgcrypt-master\libgcrypt-master\SMP\LINK	1
As we all known, libgcrypt depends on libgpg-error,but I cannot found libgpg-error anywhere. Do I need to compile it by myself?

**Comment by Sibras** [comment]
Yes you also need the dependencies. Which are also provided by ShiftMediaProject in multiple ways. But the easiest is to run the .bat script located next to gcrypt visual studio project called 'project_get_dependencies.bat'

**Comment by bopin2020** [comment]
Thank you very much! Your work is awesome. I finally compile it successfully.
How to use?   Some steps:
1. Firstly  git clone https://github.com/ShiftMediaProject/libgcrypt
2. Secondly, cd to SMP folder, please be sure you have git executable in path environment before running project_get_dependencies.bat and then git clone libgpg-error project under the same directory with libgcrypt automactically by project_get_dependencies.bat
3. Thridly, cd libgpg-error\SMP, open libgpg-error.sln to compile it that output libgpg-error.lib
4. Finally cd libgcrypt\SMP, open libgcrypt.sln and select compile output target static lib or Debug dll, for the latter you need to add include header and link libgpg-error.lib. After these steps, you will compile libgcrypt project successfully.
