### ISSUE TITLE
Error in test t-ed25519.c

### ISSUE THREAD

**Issue by Gindeles** [ShiftMediaProject/libgcrypt#8]
I needed to verify the signature (curve ed25519). I took the t-ed25519.c test to check the performance. But gcry_pk_sign returned an error. What could be the problem? Similar problem on the t-ecdsa test as well.
Fork the repository along with the test project at this link (https://github.com/Gindeles/libgcrypt). 
Test project added to libgcrypt_deps.sln

* Operating System and Version: Windows 11
* Compiler and Version(s): VS 2022 17.8.3
![image](https://github.com/ShiftMediaProject/libgcrypt/assets/66302245/8d9e8d22-dca5-4262-8022-232332074beb)

**Comment by Sibras** [comment]
No idea, this project doesnt change anything apart from what is required to get gcrypt to build with msvc. Debugging the test may provide you with more insights.

**Comment by Gindeles** [comment]
I have given a screenshot from the debugging of the test project and a link to the project itself, there is a lot of math inside the function that doesn't work. I assume that there may be a problem with memory allocation, or the sizes of some structures are incorrect when compiling under msvc. Perhaps something needs to be initialized additionally in the test project under msvc. I hope someone can debug the test project and understand the reason. 

P.S. earlier the sha and aes functionality I need worked correctly.

**Comment by Gindeles** [comment]
The problem seems to be in this define BYTES_PER_MPI_LIMB.
In the original, something like:
```
/* This file defines some basic constants for the MPI machinery.
 * AMD64 compiled for the x32 ABI is special and thus we can't use the
 * standard values for this ABI.  */
#if __GNUC__ >= 3 && defined(__x86_64__) && defined(__ILP32__)
#define BYTES_PER_MPI_LIMB 8
#else
#define BYTES_PER_MPI_LIMB  (SIZEOF_UNSIGNED_LONG)
#endif
```

gcry_pk_sign function completed successfully, but failed at line 312
 if (strcmp (sig_rs_string, sig))

**Comment by Gindeles** [comment]
Problem solved
It was necessary to change the value in 2 places
`#define BYTES_PER_MPI_LIMB 8`
\mpi\generic\mpi-asm-defs.h
\SMP\mpi\mpi-asm-defs.h

**Comment by Sibras** [comment]
Nice catch, Ive pushed a commit to master that should fix this in tree (while also working for 32bit)

**Comment by Gindeles** [comment]
I have tests in both configurations (x32 and x64) pass only if BYTES_PER_MPI_LIMB is always 8 bytes

**Comment by Sibras** [comment]
There was an error in some of the bit functions on msvc that was cuasing the 32bit mpi limb errors when BYTES_PER_MPI_LIMB was 4. Ive pushed an update that should fix the issue.

**Comment by Gindeles** [comment]
Thank you, everything works great now, at least all my tests passed
